### ISSUE TITLE
Question: How does autogrow work?

### ISSUE THREAD

**Issue by dineshbvadhia** [Dobatymo/lmdb-python-dbm#5]
Hi. I'm trying to understand how autogrow works from the code below. Could you please explain? Thanks
```
except lmdb.MapFullError:
    if not self.autogrow:
        raise
    new_map_size = self.map_size * 2
    self.map_size = new_map_size
    logger.info(self.autogrow_msg, self.env.path(), new_map_size)
```

**Comment by Dobatymo** [comment]
Well the code should explain it. When the DB is full, the db size will be doubled. Assigning to `map_size` calls lmdb `set_mapsize`.

**Comment by dineshbvadhia** [comment]
Ah got it. Thanks
