### ISSUE TITLE
Add init keyword pass through?

### ISSUE THREAD

**Issue by azaroth42** [Dobatymo/lmdb-python-dbm#7]
Further to #6, it would be valuable to allow pass-through of keywords on the Lmdb.open() function to the Environment's constructor. Then we could do:

```
cxn = Lmdb.open('file.lmdb', readahead=False)
```
for example.

It's currently hard to override the open function on a subclass if you want to respect `n` as a flag, as the module doesn't export the remove_lmdbm() function.

**Comment by Dobatymo** [comment]
@azaroth42 I will add a way to passthrough keywords. And you can import the remove function like this `from lmdbm.lmdbm import remove_lmdbm`

**Comment by Dobatymo** [comment]
Fixed https://github.com/Dobatymo/lmdb-python-dbm/releases/tag/v0.0.6
